target("math_sparse_matrix_proxy_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("sparse_matrix_proxy_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_sparse_matrix_proxy", "math_dok_matrix", "math_lil_matrix", "math_coo_matrix", "math_csc_matrix", "math_csr_matrix")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_sparse_matrix_proxy_test")
target_end()

target("math_dok_matrix_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("dok_matrix_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_dok_matrix", "math_lil_matrix", "math_coo_matrix", "math_csc_matrix", "math_csr_matrix")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_dok_matrix_test")
target_end()

target("math_lil_matrix_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("lil_matrix_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_lil_matrix", "math_dok_matrix", "math_coo_matrix", "math_csc_matrix", "math_csr_matrix")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_lil_matrix_test")
target_end()

target("math_coo_matrix_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("coo_matrix_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_coo_matrix", "math_dok_matrix", "math_lil_matrix", "math_csc_matrix", "math_csr_matrix")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_coo_matrix_test")
target_end()

target("math_csc_matrix_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("csc_matrix_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_dok_matrix", "math_lil_matrix", "math_coo_matrix", "math_csr_matrix")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_csc_matrix_test")
target_end()

target("math_csr_matrix_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("csr_matrix_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_csr_matrix", "math_dok_matrix", "math_lil_matrix", "math_coo_matrix", "math_csc_matrix")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_csr_matrix_test")
target_end()
