target("math_curve_proxy_test")
    add_rules("boyle.cxx.test")
    add_files("curve_proxy_test.cpp")
    add_deps("math_curve_proxy", "math_piecewise_linear_curve", "math_piecewise_cubic_curve", "math_piecewise_quintic_curve")
target_end()

target("math_piecewise_linear_curve2_test")
    add_rules("boyle.cxx.test")
    add_files("piecewise_linear_curve2_test.cpp")
    add_deps("math_piecewise_linear_curve")
target_end()

target("math_piecewise_cubic_curve2_test")
    add_rules("boyle.cxx.test")
    add_files("piecewise_cubic_curve2_test.cpp")
    add_deps("math_piecewise_cubic_curve")
target_end()

target("math_piecewise_quintic_curve2_test")
    add_rules("boyle.cxx.test")
    add_files("piecewise_quintic_curve2_test.cpp")
    add_deps("math_piecewise_quintic_curve")
target_end()

target("math_piecewise_linear_curve3_test")
    add_rules("boyle.cxx.test")
    add_files("piecewise_linear_curve3_test.cpp")
    add_deps("math_piecewise_linear_curve")
target_end()

target("math_piecewise_cubic_curve3_test")
    add_rules("boyle.cxx.test")
    add_files("piecewise_cubic_curve3_test.cpp")
    add_deps("math_piecewise_cubic_curve")
target_end()

target("math_piecewise_quintic_curve3_test")
    add_rules("boyle.cxx.test")
    add_files("piecewise_quintic_curve3_test.cpp")
    add_deps("math_piecewise_quintic_curve")
target_end()
