target("math_curve_proxy_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("curve_proxy_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_curve_proxy", "math_piecewise_linear_curve", "math_piecewise_cubic_curve", "math_piecewise_quintic_curve")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_curve_proxy_test")
target_end()

target("math_piecewise_linear_curve2_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("piecewise_linear_curve2_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_piecewise_linear_curve")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_piecewise_linear_curve2_test")
target_end()

target("math_piecewise_cubic_curve2_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("piecewise_cubic_curve2_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_piecewise_cubic_curve")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_piecewise_cubic_curve2_test")
target_end()

target("math_piecewise_quintic_curve2_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("piecewise_quintic_curve2_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_piecewise_quintic_curve")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_piecewise_quintic_curve2_test")
target_end()

target("math_piecewise_linear_curve3_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("piecewise_linear_curve3_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_piecewise_linear_curve")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_piecewise_linear_curve3_test")
target_end()

target("math_piecewise_cubic_curve3_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("piecewise_cubic_curve3_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_piecewise_cubic_curve")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_piecewise_cubic_curve3_test")
target_end()

target("math_piecewise_quintic_curve3_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("piecewise_quintic_curve3_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_piecewise_quintic_curve")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_piecewise_quintic_curve3_test")
target_end()
