includes("problems/xmake.lua")
includes("solvers/xmake.lua")

target("cvxopm_settings")
    set_kind("headeronly")
    add_includedirs("$(projectdir)/src", {public = true})
    add_headerfiles("settings.hpp")
    add_packages("boost", {public = true})
    add_deps("common_aligned_memory_resource")
target_end()

target("cvxopm_result")
    set_kind("headeronly")
    add_includedirs("$(projectdir)/src", {public = true})
    add_headerfiles("result.hpp")
    add_packages("boost", {public = true})
target_end()

target("cvxopm_info")
    set_kind("headeronly")
    add_includedirs("$(projectdir)/src", {public = true})
    add_headerfiles("info.hpp")
    add_packages("boost", {public = true})
target_end()
