includes("models/xmake.lua")

target("kinetics_dualism")
    set_kind("headeronly")
    add_headerfiles("dualism.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
target_end()

target("kinetics_motion")
    set_kind("headeronly")
    add_headerfiles("motion.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("boost", {public = true})
    add_deps("math_piecewise_quintic_function")
target_end()

target("kinetics_route_line")
    set_kind("headeronly")
    add_headerfiles("route_line.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("boost", {public = true})
    add_deps("math_piecewise_quintic_curve", "math_utils", "math_vec2")
target_end()

target("kinetics_path")
    set_kind("headeronly")
    add_headerfiles("path.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("boost", {public = true})
    add_deps("math_piecewise_quintic_curve", "math_utils", "math_vec2")
target_end()

target("kinetics_fence")
    set_kind("headeronly")
    add_headerfiles("fence.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("boost", {public = true})
    add_deps("kinetics_dualism", "math_concepts", "math_piecewise_linear_function")
target_end()

target("kinetics_border")
    set_kind("headeronly")
    add_headerfiles("border.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("boost", {public = true})
    add_deps("kinetics_dualism", "math_concepts", "math_piecewise_linear_curve", "math_vec2")
target_end()
