target("math_function_proxy_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("function_proxy_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_function_proxy", "math_piecewise_linear_function", "math_piecewise_cubic_function", "math_piecewise_quintic_function")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_function_proxy_test")
target_end()

target("math_piecewise_linear_function1_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("piecewise_linear_function1_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_piecewise_linear_function", "math_utils")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_piecewise_linear_function1_test")
target_end()

target("math_piecewise_cubic_function1_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("piecewise_cubic_function1_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_piecewise_cubic_function")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_piecewise_cubic_function1_test")
target_end()

target("math_piecewise_quintic_function1_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("piecewise_quintic_function1_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_piecewise_quintic_function")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_piecewise_quintic_function1_test")
target_end()
