target("cvxopm_osqp_solver")
    set_kind("$(kind)")
    add_files("osqp_solver.cpp")
    add_headerfiles("osqp_solver.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("boost", {public = true})
    add_packages("osqp", {public = true})
    add_deps("math_csc_matrix", "cvxopm_qp_problem", "cvxopm_settings", "cvxopm_result", "cvxopm_info")
target_end()

target("cvxopm_lnsrch_solver")
    set_kind("headeronly")
    add_headerfiles("lnsrch_solver.hpp", "detail/lnsrch.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_deps("math_vectorx", "math_mdfunction_proxy", "cvxopm_dense_problem", "cvxopm_settings", "cvxopm_result", "cvxopm_info")
target_end()

target("cvxopm_bfgs_solver")
    set_kind("headeronly")
    add_headerfiles("bfgs_solver.hpp", "detail/lnsrch.hpp", "detail/bfgs.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_deps("math_vectorx", "math_matrixx", "math_mdfunction_proxy", "cvxopm_dense_problem", "cvxopm_settings", "cvxopm_result", "cvxopm_info")
target_end()

target("cvxopm_lbfgs_solver")
    set_kind("headeronly")
    add_headerfiles("bfgs_solver.hpp", "detail/lnsrch.hpp", "detail/lbfgs.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_deps("math_vectorx", "math_mdfunction_proxy", "cvxopm_dense_problem", "cvxopm_settings", "cvxopm_result", "cvxopm_info")
target_end()

target("cvxopm_amoeba_solver")
    set_kind("headeronly")
    add_headerfiles("amoeba_solver.hpp", "detail/amoeba.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_deps("math_vectorx", "math_mdfunction_proxy", "cvxopm_dense_problem", "cvxopm_settings", "cvxopm_result", "cvxopm_info")
target_end()
