rule("boyle.cxx.test")
    on_load(function (target)
        target:set("kind", "binary")
        target:set("default", false)
        target:set("group", "tests")
        target:add("includedirs", "$(projectdir)/src")
        target:add("packages", "cxxopts", "doctest", "matplotplusplus")
    end)
    after_load(function (target)
        target:add("tests", target:name())
    end)
rule_end()
