target("math_vector_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("vector_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_vector_view", "math_vector", "math_vectorx")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_vector_test")
target_end()

target("math_vec2_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("vec2_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_vec2")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_vec2_test")
target_end()

target("math_vec3_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("vec3_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_vec3")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_vec3_test")
target_end()

target("math_matrix_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("matrix_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_matrix_view", "math_matrix", "math_matrixx")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_matrix_test")
target_end()

target("math_lu_dcmp_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("lu_dcmp_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_type_traits", "math_lu_dcmp", "math_vector", "math_vectorx", "math_matrix", "math_matrixx")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_lu_dcmp_test")
target_end()

target("math_qr_dcmp_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("qr_dcmp_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_type_traits", "math_qr_dcmp", "math_vector", "math_vectorx", "math_matrix", "math_matrixx")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_qr_dcmp_test")
target_end()
