target("math_vector_test")
    add_rules("boyle.cxx.test")
    add_files("vector_test.cpp")
    add_deps("math_vector_view", "math_vector", "math_vectorx")
target_end()

target("math_vec2_test")
    add_rules("boyle.cxx.test")
    add_files("vec2_test.cpp")
    add_deps("math_vec2")
target_end()

target("math_vec3_test")
    add_rules("boyle.cxx.test")
    add_files("vec3_test.cpp")
    add_deps("math_vec3")
target_end()

target("math_matrix_test")
    add_rules("boyle.cxx.test")
    add_files("matrix_test.cpp")
    add_deps("math_matrix_view", "math_matrix", "math_matrixx")
target_end()

target("math_lu_dcmp_test")
    add_rules("boyle.cxx.test")
    add_files("lu_dcmp_test.cpp")
    add_deps("math_type_traits", "math_lu_dcmp", "math_vector", "math_vectorx", "math_matrix", "math_matrixx")
target_end()

target("math_qr_dcmp_test")
    add_rules("boyle.cxx.test")
    add_files("qr_dcmp_test.cpp")
    add_deps("math_type_traits", "math_qr_dcmp", "math_vector", "math_vectorx", "math_matrix", "math_matrixx")
target_end()
