target("kinetics_route_line_cubic_acc_model_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("route_line_cubic_acc_model_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("kinetics_route_line_cubic_acc_model")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("kinetics_route_line_cubic_acc_model_test")
target_end()

target("kinetics_route_line_quintic_acc_model_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("route_line_quintic_acc_model_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("kinetics_route_line_quintic_acc_model")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("kinetics_route_line_quintic_acc_model_test")
target_end()

target("kinetics_route_line_cubic_offset_model_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("route_line_cubic_offset_model_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("kinetics_route_line_cubic_offset_model")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("kinetics_route_line_cubic_offset_model_test")
target_end()

target("kinetics_route_line_quintic_offset_model_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("route_line_quintic_offset_model_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("kinetics_route_line_quintic_offset_model")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("kinetics_route_line_quintic_offset_model_test")
target_end()
