target("cvxopm_osqp_solver_test")
    add_rules("boyle.cxx.test")
    add_files("osqp_solver_test.cpp")
    add_packages("boost")
    add_deps("cvxopm_qp_problem", "cvxopm_settings", "cvxopm_result", "cvxopm_info", "cvxopm_osqp_solver")
target_end()

target("cvxopm_lnsrch_solver_test")
    add_rules("boyle.cxx.test")
    add_files("lnsrch_solver_test.cpp")
    add_deps("math_vectorx", "math_matrixx", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem", "cvxopm_lnsrch_solver")
target_end()

target("cvxopm_bfgs_solver_test")
    add_rules("boyle.cxx.test")
    add_files("bfgs_solver_test.cpp")
    add_deps("math_vectorx", "math_matrixx", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem", "cvxopm_bfgs_solver")
target_end()

target("cvxopm_lbfgs_solver_test")
    add_rules("boyle.cxx.test")
    add_files("lbfgs_solver_test.cpp")
    add_deps("math_vectorx", "math_matrixx", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem", "cvxopm_lbfgs_solver")
target_end()

target("cvxopm_amoeba_solver_test")
    add_rules("boyle.cxx.test")
    add_files("amoeba_solver_test.cpp")
    add_deps("math_vectorx", "math_matrixx", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem", "cvxopm_amoeba_solver")
target_end()
