target("cvxopm_osqp_solver_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("osqp_solver_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_packages("boost")
    add_deps("cvxopm_qp_problem", "cvxopm_settings", "cvxopm_result", "cvxopm_info", "cvxopm_osqp_solver")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("cvxopm_osqp_solver_test")
target_end()

target("cvxopm_lnsrch_solver_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("lnsrch_solver_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_vectorx", "math_matrixx", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem", "cvxopm_lnsrch_solver")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("cvxopm_lnsrch_solver_test")
target_end()

target("cvxopm_bfgs_solver_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("bfgs_solver_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_vectorx", "math_matrixx", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem", "cvxopm_bfgs_solver")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("cvxopm_bfgs_solver_test")
target_end()

target("cvxopm_lbfgs_solver_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("lbfgs_solver_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_vectorx", "math_matrixx", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem", "cvxopm_lbfgs_solver")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("cvxopm_lbfgs_solver_test")
target_end()

target("cvxopm_amoeba_solver_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("amoeba_solver_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_vectorx", "math_matrixx", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem", "cvxopm_amoeba_solver")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("cvxopm_amoeba_solver_test")
target_end()
