target("math_mdfunction_proxy_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("mdfunction_proxy_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_mdfunction_proxy", "math_vector", "math_vectorx", "math_matrix", "math_matrixx", "math_linear_mdfunction", "math_quadratic_mdfunction")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_mdfunction_proxy_test")
target_end()

target("math_linear_mdfunction_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("linear_mdfunction_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_vector", "math_vectorx", "math_linear_mdfunction")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_linear_mdfunction_test")
target_end()

target("math_quadratic_mdfunction_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("quadratic_mdfunction_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_vector", "math_vectorx", "math_matrix", "math_matrixx", "math_quadratic_mdfunction")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_quadratic_mdfunction_test")
target_end()

target("math_rosenbrock_function_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("rosenbrock_function_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_vec2", "math_rosenbrock_function")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_rosenbrock_function_test")
target_end()
