includes("curves/xmake.lua")
includes("functions/xmake.lua")
includes("mdfunctions/xmake.lua")
includes("dense/xmake.lua")
includes("sparse/xmake.lua")

target("math_fft_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("fft_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_fft")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_fft_test")
target_end()

target("math_chebyshev_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("chebyshev_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_chebyshev", "math_utils")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_chebyshev_test")
target_end()

target("math_cubic_interpolation_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("cubic_interpolation_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_cubic_interpolation")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_cubic_interpolation_test")
target_end()

target("math_quintic_interpolation_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("quintic_interpolation_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_quintic_interpolation")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("math_quintic_interpolation_test")
target_end()
