includes("curves/xmake.lua")
includes("functions/xmake.lua")
includes("mdfunctions/xmake.lua")
includes("dense/xmake.lua")
includes("sparse/xmake.lua")

target("math_fft_test")
    add_rules("boyle.cxx.test")
    add_files("fft_test.cpp")
    add_deps("math_fft")
target_end()

target("math_chebyshev_test")
    add_rules("boyle.cxx.test")
    add_files("chebyshev_test.cpp")
    add_deps("math_chebyshev", "math_utils")
target_end()

target("math_cubic_interpolation_test")
    add_rules("boyle.cxx.test")
    add_files("cubic_interpolation_test.cpp")
    add_deps("math_cubic_interpolation")
target_end()

target("math_quintic_interpolation_test")
    add_rules("boyle.cxx.test")
    add_files("quintic_interpolation_test.cpp")
    add_deps("math_quintic_interpolation")
target_end()
