target("math_curve_proxy")
    set_kind("headeronly")
    add_headerfiles("curve_proxy.hpp", "sl.hpp", "slv.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("msft_proxy4", {public = true})
    add_deps("math_concepts", "math_vec2", "math_vec3")
target_end()

target("math_piecewise_linear_curve")
    set_kind("headeronly")
    add_headerfiles("piecewise_linear_curve.hpp", "sl.hpp", "slv.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("boost", {public = true})
    add_deps("common_aligned_allocator", "math_piecewise_linear_function", "math_utils", "math_vec2", "math_vec3")
target_end()

target("math_piecewise_cubic_curve")
    set_kind("headeronly")
    add_headerfiles("piecewise_cubic_curve.hpp", "sl.hpp", "slv.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("boost", {public = true})
    add_deps("common_aligned_allocator", "math_cubic_interpolation", "math_piecewise_cubic_function", "math_utils", "math_vec2", "math_vec3")
target_end()

target("math_piecewise_quintic_curve")
    set_kind("headeronly")
    add_headerfiles("piecewise_quintic_curve.hpp", "sl.hpp", "slv.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("boost", {public = true})
    add_deps("common_aligned_allocator", "math_piecewise_quintic_function", "math_quintic_interpolation", "math_utils", "math_vec2", "math_vec3")
target_end()
