target("kinetics_route_line_cubic_acc_model")
    set_kind("headeronly")
    add_headerfiles("route_line_cubic_acc_model.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_deps("common_logging", "cvxopm_qp_problem", "cvxopm_osqp_solver", "kinetics_motion", "kinetics_fence")
target_end()

target("kinetics_route_line_quintic_acc_model")
    set_kind("headeronly")
    add_headerfiles("route_line_quintic_acc_model.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_deps("common_logging", "cvxopm_qp_problem", "cvxopm_osqp_solver", "kinetics_motion", "kinetics_fence")
target_end()

target("kinetics_route_line_cubic_offset_model")
    set_kind("headeronly")
    add_headerfiles("route_line_cubic_offset_model.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_deps("common_logging", "math_piecewise_cubic_curve", "cvxopm_qp_problem", "cvxopm_osqp_solver", "kinetics_path", "kinetics_border")
target_end()

target("kinetics_route_line_quintic_offset_model")
    set_kind("headeronly")
    add_headerfiles("route_line_quintic_offset_model.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_deps("common_logging", "math_piecewise_quintic_curve", "cvxopm_qp_problem", "cvxopm_osqp_solver", "kinetics_path", "kinetics_border")
target_end()
