target("math_mdfunction_proxy")
    set_kind("headeronly")
    add_headerfiles("mdfunction_proxy.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("msft_proxy4", {public = true})
target_end()

target("math_linear_mdfunction")
    set_kind("headeronly")
    add_headerfiles("linear_mdfunction.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("boost", {public = true})
    add_deps("math_concepts")
target_end()

target("math_quadratic_mdfunction")
    set_kind("headeronly")
    add_headerfiles("quadratic_mdfunction.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("boost", {public = true})
    add_deps("math_concepts")
target_end()

target("math_rosenbrock_function")
    set_kind("headeronly")
    add_headerfiles("rosenbrock_function.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("boost", {public = true})
    add_deps("math_concepts")
target_end()
