includes("curves/xmake.lua")
includes("functions/xmake.lua")
includes("mdfunctions/xmake.lua")
includes("dense/xmake.lua")
includes("sparse/xmake.lua")

target("math_type_traits")
    set_kind("headeronly")
    add_headerfiles("type_traits.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
target_end()

target("math_concepts")
    set_kind("headeronly")
    add_headerfiles("concepts.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
target_end()

target("math_fft")
    set_kind("headeronly")
    add_headerfiles("fft.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("pocketfft", {public = true})
    add_defines("POCKETFFT_NO_MULTITHREADING", {public = true})
target_end()

target("math_chebyshev")
    set_kind("headeronly")
    add_headerfiles("chebyshev.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_packages("boost", {public = true})
target_end()

target("math_utils")
    set_kind("headeronly")
    add_headerfiles("utils.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_deps("math_concepts")
target_end()

target("math_cubic_interpolation")
    set_kind("headeronly")
    add_headerfiles("cubic_interpolation.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_deps("math_concepts", "math_utils")
target_end()

target("math_quintic_interpolation")
    set_kind("headeronly")
    add_headerfiles("quintic_interpolation.hpp")
    add_includedirs("$(projectdir)/src", {public = true})
    add_deps("math_concepts", "math_cubic_interpolation")
target_end()
