target("math_function_proxy")
    set_kind("headeronly")
    add_includedirs("$(projectdir)/src", {public = true})
    add_headerfiles("function_proxy.hpp")
    add_packages("msft_proxy4", {public = true})
    add_deps("math_concepts")
target_end()

target("math_piecewise_linear_function")
    set_kind("headeronly")
    add_includedirs("$(projectdir)/src", {public = true})
    add_headerfiles("piecewise_linear_function.hpp")
    add_packages("boost", {public = true})
    add_deps("common_aligned_allocator", "math_concepts", "math_utils", "math_vec2", "math_vec3")
target_end()

target("math_piecewise_cubic_function")
    set_kind("headeronly")
    add_includedirs("$(projectdir)/src", {public = true})
    add_headerfiles("piecewise_cubic_function.hpp", "boundary_mode.hpp")
    add_packages("boost", {public = true})
    add_deps("common_aligned_allocator", "math_concepts", "math_cubic_interpolation", "math_utils", "math_vec2", "math_vec3")
target_end()

target("math_piecewise_quintic_function")
    set_kind("headeronly")
    add_includedirs("$(projectdir)/src", {public = true})
    add_headerfiles("piecewise_quintic_function.hpp", "boundary_mode.hpp")
    add_packages("boost", {public = true})
    add_deps("common_aligned_allocator", "math_concepts", "math_quintic_interpolation", "math_utils", "math_vec2", "math_vec3")
target_end()
