target("common_fsm_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("fsm_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("common_fsm", "common_logging")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("common_fsm_test")
target_end()
