ExternalProject_Add(OpenBLAS
  PREFIX ${CMAKE_CURRENT_BINARY_DIR}/_deps
  TMP_DIR ${CMAKE_CURRENT_BINARY_DIR}/_deps/openblas-tmp
  STAMP_DIR ${CMAKE_CURRENT_BINARY_DIR}/_deps/openblas-stamp
  SOURCE_DIR ${OpenBLAS_SOURCE_DIR}
  BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/_deps/openblas-build
  INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/_deps/openblas-install
  CMAKE_GENERATOR Ninja
  CMAKE_ARGS
    -DCMAKE_POLICY_VERSION_MINIMUM=3.5
    -DCMAKE_TOOLCHAIN_FILE=${CMAKE_TOOLCHAIN_FILE}
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_COMPILE_WARNING_AS_ERROR=OFF
    -DCMAKE_BINARY_DIR=<BINARY_DIR>
    -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>
    -DBUILD_SHARED_LIBS=${BUILD_SHARED_LIBS}
    -DBUILD_TESTING=OFF
    -DNOFORTRAN=ON
    -DC_LAPACK=ON
    -DDYNAMIC_ARCH=OFF
    -DUSE_THREAD=OFF
    -DUSE_OPENMP=OFF
  BUILD_BYPRODUCTS
    ${CMAKE_CURRENT_BINARY_DIR}/_deps/openblas-build/openblas.lib
  INSTALL_BYPRODUCTS
    ${CMAKE_CURRENT_BINARY_DIR}/_deps/openblas-install/lib/openblas.lib
)

set(_OPENBLAS_INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/_deps/openblas-install)
set(_OPENBLAS_INCLUDE_DIR ${_OPENBLAS_INSTALL_DIR}/include/openblas)
set(_OPENBLAS_SHARED_LIB ${_OPENBLAS_INSTALL_DIR}/lib/openblas.lib)
set(_OPENBLAS_STATIC_LIB ${_OPENBLAS_INSTALL_DIR}/lib/openblas.lib)
set(_OPENBLAS_INTERFACE_LINK_LIBRARIES "")

add_library(blas_lapack INTERFACE)
add_library(blas_lapack_static INTERFACE)

add_dependencies(blas_lapack OpenBLAS)
add_dependencies(blas_lapack_static OpenBLAS)

set(_OPENBLAS_MSVC_COMPAT_HEADER "${CMAKE_SOURCE_DIR}/cmake/openblas_msvc_compat.h")

set_target_properties(blas_lapack
  PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "BOYLE_USE_BLAS_LAPACK"
    INTERFACE_COMPILE_OPTIONS "/FI${_OPENBLAS_MSVC_COMPAT_HEADER}"
    INTERFACE_INCLUDE_DIRECTORIES "$<BUILD_INTERFACE:${_OPENBLAS_INCLUDE_DIR}>;$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>"
    INTERFACE_LINK_LIBRARIES "$<BUILD_INTERFACE:${_OPENBLAS_SHARED_LIB}>;$<INSTALL_INTERFACE:${CMAKE_INSTALL_LIBDIR}/openblas.lib>;${_OPENBLAS_INTERFACE_LINK_LIBRARIES}"
)
set_target_properties(blas_lapack_static
  PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS "BOYLE_USE_BLAS_LAPACK"
    INTERFACE_COMPILE_OPTIONS "/FI${_OPENBLAS_MSVC_COMPAT_HEADER}"
    INTERFACE_INCLUDE_DIRECTORIES "$<BUILD_INTERFACE:${_OPENBLAS_INCLUDE_DIR}>;$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>"
    INTERFACE_LINK_LIBRARIES "$<BUILD_INTERFACE:${_OPENBLAS_STATIC_LIB}>;$<INSTALL_INTERFACE:${CMAKE_INSTALL_LIBDIR}/openblas.lib>;${_OPENBLAS_INTERFACE_LINK_LIBRARIES}"
)

unset(_OPENBLAS_MSVC_COMPAT_HEADER)

if(BOYLE_ENABLE_INSTALL)
  install(
    DIRECTORY ${_OPENBLAS_INSTALL_DIR}/.
    DESTINATION ${CMAKE_INSTALL_PREFIX}
  )
  install(
    TARGETS blas_lapack blas_lapack_static
    EXPORT ${CMAKE_PROJECT_NAME}Targets
  )
endif()

set(BLAS_FOUND True CACHE INTERNAL "set BLAS found")
set(BLAS_INCLUDE_DIRS "$<BUILD_INTERFACE:${_OPENBLAS_INCLUDE_DIR}>;$<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>" CACHE INTERNAL "set BLAS include directory")
set(BLAS_LIBRARIES "$<IF:$<BOOL:${BUILD_SHARED_LIBS}>,blas_lapack,blas_lapack_static>" CACHE INTERNAL "set BLAS library")
set(BLAS_LINKER_FLAGS "" CACHE INTERNAL "set BLAS linker flags")
set(LAPACK_FOUND True CACHE INTERNAL "set LAPACK found")
set(LAPACK_INCLUDE_DIRS ${BLAS_INCLUDE_DIRS} CACHE INTERNAL "set LAPACK include directory")
set(LAPACK_LIBRARIES ${BLAS_LIBRARIES} CACHE INTERNAL "set LAPACK library")
set(LAPACK_LINKER_FLAGS "${BLAS_LINKER_FLAGS}" CACHE INTERNAL "set LAPACK linker flags")

unset(_OPENBLAS_INSTALL_DIR)
unset(_OPENBLAS_INCLUDE_DIR)
unset(_OPENBLAS_SHARED_LIB)
unset(_OPENBLAS_STATIC_LIB)
unset(_OPENBLAS_INTERFACE_LINK_LIBRARIES)
