target("cvxopm_qp_problem_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("qp_problem_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("cvxopm_qp_problem")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("cvxopm_qp_problem_test")
target_end()

target("cvxopm_dense_problem_test")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_files("dense_problem_test.cpp")
    add_includedirs("$(projectdir)/src")
    add_deps("math_utils", "math_vectorx", "math_matrixx", "math_quadratic_mdfunction", "math_rosenbrock_function", "cvxopm_dense_problem")
    add_packages("cxxopts", "doctest", "matplotplusplus")
    add_tests("cvxopm_dense_problem_test")
target_end()
