name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CFLAGS: ""
  CXXFLAGS: ""
  BUILDTYPE: "Debug"

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4

    - name: Get Date
      id: get-date
      run: |
        echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
      shell: bash

    - name: Install latest CMake and Ninja
      id: install-cmake
      uses: lukka/get-cmake@latest

    - name: Install boost
      id: install-boost
      uses: MarkusJx/install-boost@v2.4.5
      with:
        boost_version: 1.83.0
        platform_version: 22.04
        toolset: gcc
        link: static+shared
        arch: x86

    - name: Cache Outputs
      id: cache-outputs
      uses: actions/cache@v4
      with:
        path: |
          ${{github.workspace}}/out
          ${{github.workspace}}/third_party
        key: ${{runner.os}}-${{steps.get-date.outputs.date}}
        restore-keys: |
          ${{runner.os}}-

    - name: Run CMake consuming CMakePresets.json for gcc-ubuntu_x64
      uses: lukka/run-cmake@v10
      with:
        configurePreset: gcc-ubuntu_x64
        configurePresetAdditionalArgs: "['-DCMAKE_BUILD_TYPE=${{ env.BUILDTYPE }}']"
        buildPreset: gcc-ubuntu_x64
        buildPresetAdditionalArgs: "['-j', '0']"
        testPreset: gcc-ubuntu_x64
        testPresetAdditionalArgs: "['-j', '0']"
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}

    - name: Run CMake consuming CMakePresets.json for clang-ubuntu_x64
      uses: lukka/run-cmake@v10
      with:
        configurePreset: clang-ubuntu_x64
        configurePresetAdditionalArgs: "[]"
        buildPreset: clang-ubuntu_x64
        buildPresetAdditionalArgs: "['-j', '0']"
        testPreset: clang-ubuntu_x64
        testPresetAdditionalArgs: "['-j', '0']"
      env:
        BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
