name: build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  actions: write

jobs:

  linux-build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        cmake_preset: [linux-clang-x64]
        build_type: [Release, Debug, RelWithDebInfo, MinSizeRel]
        build_shared: [ON]
        use_blas_lapack: [ON]
        use_boost_unordered: [ON]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.cmake_preset }}.${{ matrix.build_type }}.build-shared-${{ matrix.build_shared }}.blas-lapack-${{ matrix.use_blas_lapack }}.boost-unordered-${{ matrix.use_boost_unordered }}
    env:
      GCC_VERSION: '14'
      CLANG_VERSION: '20'

    steps:
    - name: Checkout repository
      id: checkout-repository
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Install gcc prerequisites on Linux (Ubuntu)
      id: install-prerequisites-linux-gcc
      if: matrix.cmake_preset == 'linux-gcc-x64'
      run: |
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-${{ env.GCC_VERSION }} ${{ env.GCC_VERSION }}
        sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-${{ env.GCC_VERSION }} ${{ env.GCC_VERSION }}
        sudo update-alternatives --install /usr/bin/gfortran gfortran /usr/bin/gfortran-${{ env.GCC_VERSION }} ${{ env.GCC_VERSION }}
        sudo update-alternatives --set gcc /usr/bin/gcc-${{ env.GCC_VERSION }}
        sudo update-alternatives --set g++ /usr/bin/g++-${{ env.GCC_VERSION }}
        sudo update-alternatives --set gfortran /usr/bin/gfortran-${{ env.GCC_VERSION }}
      shell: bash

    - name: Install clang prerequisites on Linux (Ubuntu)
      id: install-prerequisites-linux-clang
      if: matrix.cmake_preset == 'linux-clang-x64'
      run: |
        sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)" ${{ env.CLANG_VERSION }} all
        sudo apt-get install -y flang-${{ env.CLANG_VERSION }} libflang-${{ env.CLANG_VERSION }}-dev
        sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-${{ env.CLANG_VERSION }} ${{ env.CLANG_VERSION }}
        sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-${{ env.CLANG_VERSION }} ${{ env.CLANG_VERSION }}
        sudo update-alternatives --install /usr/bin/flang flang /usr/bin/flang-${{ env.CLANG_VERSION }} ${{ env.CLANG_VERSION }}
        sudo update-alternatives --install /usr/bin/lld lld /usr/bin/lld-${{ env.CLANG_VERSION }} ${{ env.CLANG_VERSION }}
        sudo update-alternatives --install /usr/bin/ld.lld ld.lld /usr/bin/ld.lld-${{ env.CLANG_VERSION }} ${{ env.CLANG_VERSION }}
        sudo update-alternatives --set clang /usr/bin/clang-${{ env.CLANG_VERSION }}
        sudo update-alternatives --set clang++ /usr/bin/clang++-${{ env.CLANG_VERSION }}
        sudo update-alternatives --set flang /usr/bin/flang-${{ env.CLANG_VERSION }}
        sudo update-alternatives --set lld /usr/bin/lld-${{ env.CLANG_VERSION }}
        sudo update-alternatives --set ld.lld /usr/bin/ld.lld-${{ env.CLANG_VERSION }}
      shell: bash

    - name: Setup vcpkg
      id: setup-vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Install latest CMake and Ninja
      id: install-cmake
      uses: lukka/get-cmake@latest

    - name: Setup ccache
      id: setup-ccache
      uses: Chocobo1/setup-ccache-action@v1
      with:
        store_cache: false
        restore_cache: false
        remove_stale_cache: true
        override_cache_key: ccache_${{ matrix.cmake_preset }}_${{ matrix.build_type }}_build-shared-${{ matrix.build_shared }}_blas-lapack-${{ matrix.use_blas_lapack }}_boost-unordered-${{ matrix.use_boost_unordered }}

    - name: Run CMake consuming CMakePresets.json for ${{ matrix.cmake_preset }} ${{ matrix.build_type }}
      id: run-cmake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: ${{ matrix.cmake_preset }}
        configurePresetAdditionalArgs: "['-DCMAKE_BUILD_TYPE=${{ matrix.build_type }}', '-DBUILD_SHARED_LIBS=${{ matrix.build_shared }}', '-DBOYLE_USE_BLAS_LAPACK=${{ matrix.use_blas_lapack }}', '-DBOYLE_USE_BOOST_UNORDERED=${{ matrix.use_boost_unordered }}']"
        buildPreset: ${{ matrix.cmake_preset }}
        buildPresetAdditionalArgs: "[]"
        testPreset: ${{ matrix.cmake_preset }}
        testPresetAdditionalArgs: "[]"


  windows-build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        cmake_preset: [windows-msvc-x64]
        build_type: [Release, Debug, RelWithDebInfo, MinSizeRel]
        build_shared: [OFF]
        use_blas_lapack: [OFF]
        use_boost_unordered: [OFF]

    runs-on: ${{ matrix.os }}
    name: ${{ matrix.cmake_preset }}.${{ matrix.build_type }}.build-shared-${{ matrix.build_shared }}.blas-lapack-${{ matrix.use_blas_lapack }}.boost-unordered-${{ matrix.use_boost_unordered }}

    steps:
    - name: Checkout repository
      id: checkout-repository
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Install MSVC prerequisites on Windows
      id: install-prerequisites-windows-msvc
      uses: TheMrMilchmann/setup-msvc-dev@v4
      with:
        arch: x64

    - name: Setup vcpkg
      id: setup-vcpkg
      uses: lukka/run-vcpkg@v11

    - name: Install latest CMake and Ninja
      id: install-cmake
      uses: lukka/get-cmake@latest

    - name: Setup ccache
      id: setup-ccache
      uses: Chocobo1/setup-ccache-action@v1
      with:
        store_cache: false
        restore_cache: false
        remove_stale_cache: true
        windows_compile_environment: msvc
        override_cache_key: ccache_${{ matrix.cmake_preset }}_${{ matrix.build_type }}_build-shared-${{ matrix.build_shared }}_blas-lapack-${{ matrix.use_blas_lapack }}_boost-unordered-${{ matrix.use_boost_unordered }}

    - name: Run CMake consuming CMakePresets.json for ${{ matrix.cmake_preset }} ${{ matrix.build_type }}
      id: run-cmake
      uses: lukka/run-cmake@v10
      with:
        configurePreset: ${{ matrix.cmake_preset }}
        configurePresetAdditionalArgs: "['-DCMAKE_BUILD_TYPE=${{ matrix.build_type }}', '-DBUILD_SHARED_LIBS=${{ matrix.build_shared }}', '-DBOYLE_USE_BLAS_LAPACK=${{ matrix.use_blas_lapack }}', '-DBOYLE_USE_BOOST_UNORDERED=${{ matrix.use_boost_unordered }}']"
        buildPreset: ${{ matrix.cmake_preset }}
        buildPresetAdditionalArgs: "[]"
        testPreset: ${{ matrix.cmake_preset }}
        testPresetAdditionalArgs: "[]"
